#/usr/bin/env sh

source ~/.env

BASH=$(which bash)
ZSH=$(which zsh)

USERSHELL=$(getent passwd $LOGNAME | cut -d: -f7)

if test "$USERSHELL" == "/usr/bin/zsh"
then
	source ~/.zshrc
else
	source ~/.bash_profile
fi