#!/usr/bin/env bash
[ -z "$PS1" ] && exit 0


. ~/.bash_profile

SB="/opt/sublime_text/sublime_text -w"
VIM=$(which vim)
VI=$(which vi)


for EDI in "$SB" "$VIM" "$VI"
do
	if [ -f "$EDI" ]; then
		export EDITOR="$EDI"
		export GIT_EDITOR="$EDI"
		break
	fi
done